services:
  mariadb:
    image: mariadb:11.3.2
    container_name: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - db-con
      - mariadb-man

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb
      - PMA_VERBOSE="Rotarty Pub DB"
      - UPLOAD_LIMIT=8M
    networks:
      - reverse-proxy
      - mariadb-man
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.rotarypub.se`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"


networks:
  reverse-proxy:
    external: true
  db-con:
    external: true
  mariadb-man:

volumes:
  mariadb-data:
    external: true
    name: "database_mariadb-data"
